Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/? HTTP/1.1" 500 182854
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/? HTTP/1.1" 500 182854
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 182822
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 182822
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 189005
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 189005
Internal Server Error: /admin/audit_log/auditlog/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: audit_log_auditlog.change_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ~~~^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: audit_log_auditlog.change_message
"GET /admin/audit_log/auditlog/ HTTP/1.1" 500 189005
Not Found: /dashboard/admin
"GET /dashboard/admin HTTP/1.1" 404 4326
Internal Server Error: /add-item
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/Inventory_management_system/Inventory/views.py", line 82, in get
    formset = InventoryItemFormSet(queryset=InventoryItem.objects.none())  # Empty formset
TypeError: BaseFormSet.__init__() got an unexpected keyword argument 'queryset'
"GET /add-item HTTP/1.1" 500 89971
Internal Server Error: /add-item
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/Inventory_management_system/Inventory/views.py", line 83, in get
    return render(request, self.template_name, {'formset': formset})
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 4: 'block'. Looking for one of: endblock.
"GET /add-item HTTP/1.1" 500 197789
Internal Server Error: /add-item
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/Inventory_management_system/Inventory/views.py", line 83, in get
    return render(request, self.template_name, {'formset': formset})
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 4: 'block'. Looking for one of: endblock.
"GET /add-item HTTP/1.1" 500 197789
Internal Server Error: /add-item
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/Inventory_management_system/Inventory/views.py", line 83, in get
    return render(request, self.template_name, {'formset': formset})
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 4: 'block'. Looking for one of: endblock.
"GET /add-item HTTP/1.1" 500 197787
Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/Inventory_management_system/Inventory/views.py", line 32, in get
    return render(request, 'Inventory/dashboard.html', {'items': items, 'LOW_QUANTITY': LOW_QUANTITY})
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/defaulttags.py", line 976, in do_if
    nodelist = parser.parse(("endif",))
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 523, in parse
    self.unclosed_block_tag(parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/lesliena/Documents/GitHub/Warehouse-Inventory-Management-Tool/IMS/env/lib/python3.13/site-packages/django/template/base.py", line 586, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 45: 'for'. Looking for one of: empty, endfor.
"GET /dashboard/ HTTP/1.1" 500 230666
